### ISSUE TITLE
Getting 503 error on aplication uploaded at Digital ocean

### ISSUE THREAD

**Issue by henriqu3** [serp-spider/http-client-curl#19]
Hi guys.

I've been developed an aplication with Laravel lumen using your lib.

At my local computer works fine, but, when I uploaded to digital ocean server, I got 503 error server.

What could be?

Follow the error: ` https://google.com/search?q=Embalagem+a+v%C3%A1cuo&num=100 has an invalid status code: '503'`

**Comment by gsouf** [comment]
Hi @henriqu3 

I suspect it to be because you are using shared ip and that those ip are blacklisted by google. If you want to scrape google from the cloud, you will have to use proxy. You can find further instructions here:

- [general proxy documentation](https://serp-spider.github.io/documentation/proxy/)
- [use proxy for a browser instance](https://serp-spider.github.io/documentation/browser/#using-a-proxy)

If you have any issue with proxy, feel free to reopen the issue or to reach via gitter

**Comment by henriqu3** [comment]
I'm using a anonymous proxy created by me on diferents ips and request 100 results per page every minute.
But, google is still killing my applications after 1 hours more or less.
This recent update on serps has any influence on this ?
